<?php $this->notices()?>
<div id="main" role="main">
    <h3 class="page-header">用例 - Example</h3>
    <p>Singを利用した実装の用例を記録するページ。ボタンを押下して各用例の実装例ページを確認して下さい。</p>

    <div class="mainDetail-form">
        <ul>

            <li>
                <span>Ex01.トークンを利用したCSRF（クロスサイトリクエストフォージェリ）対策</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex01/">Ex01</a>
                </p>
            </li>
            <li>
                <span>Ex02.モデルオブジェクトの自動生成</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex02/">Ex02</a>
                </p>
            </li>
            <li>
                <span>Ex03.プラグインの実行順</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex03/">Ex03</a>
                </p>
            </li>
            <li>
                <span>Ex04.会員登録フォーム・サンプル</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/signup/">Ex04</a>
                </p>
            </li>
            <li>
                <span>Ex05.バリデーション</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex05/">Ex05</a>
                </p>
            </li>
            <li>
                <span>Ex06.詳細ページのレイアウトサンプル</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex06/">Ex06</a>
                </p>
            </li>
            <li>
                <span>Ex07.PHPUnit画面実行サンプル</span>
                <p class="mainDetail-execButton">
                    <a class="btn btn-default" href="/example/ex07/">Ex07</a>
                </p>
            </li>

        </ul>
    </div>
</div>