<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?php echo $this->title ?></title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/common-admin.css" rel="stylesheet">
    <link href="/css/<?php echo $this->contentCss ?>" rel="stylesheet">
    <script src="/js/jquery-1.10.2.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/common.js"></script>
    <?php $this->customJs() ?>
</head>
<body>

<div class="container">

<?php echo $this->render('header_admin.phtml') ?>

<?php echo $this->render('nav_admin.phtml') ?>

<?php echo $this->layout()->content ?>

<?php echo $this->render('footer_admin.phtml') ?>

</div>

</body>
</html>