<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title><?php echo $this->title ?></title>
<link rel="stylesheet" href="/css/bootstrap.min.css" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" >
<link rel="stylesheet" href="/css/common.css" />
<script src="/js/jquery-1.10.2.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/common.js"></script>
</head>
<body>

<div class="container">

<?php echo $this->render('header.phtml') ?>

<?php echo $this->render('nav.phtml') ?>

<div id="contents">

<?php if (!$this->isError()):?>
    <?php echo $this->render('breadcrumb.phtml') ?>
<?php endif;?>

<?php echo $this->layout()->content ?>
</div>

<?php echo $this->render('footer.phtml') ?>

</div>

</body>
</html>