<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><strong>Sing</strong></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                <li><a href="/example/">用例</a></li>
                <?php if ($this->isLogined()):?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-user"></span>&nbsp;<?php echo Sing_Session::getAuthUser('email')?>
                            (<?php echo Sing_Session::getAuthUser('role')?>) <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/mypage/account/">My Account</a></li>
                            <li><a href="#">Transactions</a></li>

                            <?php if ($this->isAdmin()):?>
                                <li class="divider"></li>
                                <li><a href="/admin/">Admin Top</a></li>
                            <?php endif;?>

                            <li class="divider"></li>
                            <li><a href="/login/logout/">ログアウト</a></li>
                        </ul>
                    </li>
                <?php endif;?>
            </ul>
        </div>
    </div>
</nav>
