<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin/">Admin Console</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->isLogined()):?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo Sing_Session::getAuthUser('email')?> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/">User Top</a></li>
                            <li class="divider"></li>
                            <li><a href="/admin/login/logout/">Logout</a></li>
                        </ul>
                    </li>
                <?php endif;?>
            </ul>
        </div>
    </div>
</nav>
