<?php $this->notices()?>
<div id="main" role="main">
    <h3 class="page-header">Ex06.詳細ページのレイアウトサンプル</h3>
    <p>ご本人様情報・勤務先情報を変更する場合は、「変更する」ボタンを押し、変更ページにてお手続きください。詳細ページのレイアウト・デザイン。</p>

    <div class="mainDetail">
        <h4 class="mainDetail-header">ご本人様情報</h4>

        <div class="mainDetail-form">
            <dl class="formInput-box">
                <dt class="formInput-title">郵便番号</dt>
                <dd class="formInput-inner" id="js-home_zip_code">220-0012 </dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">ご住所</dt>
                <dd class="formInput-inner" id="js-home_addr">神奈川県 横浜市西区 みなとみらい 三丁目5番1号</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">電話番号</dt>
                <dd class="formInput-inner" id="js-tel_num-mob_num">携帯電話　000-0000-0000</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">前年度ご本人様税込み年収</dt>
                <dd class="formInput-inner" id="js-income">1000万円</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">前年度配偶者様年収</dt>
                <dd class="formInput-inner" id="js-spouse_income">0万円</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">前年度世帯年収</dt>
                <dd class="formInput-inner" id="js-family_income">1000万円</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">ご家族</dt>
                <dd class="formInput-inner" id="js-family_type-household_num">配偶者あり　子供あり　（世帯人数4人以上）</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">お住まい</dt>
                <dd class="formInput-inner" id="js-live_in_sts_code-live_in_y">持家（自己所有）　（居住年数1年以上3年未満）</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">住宅ローンもしくは家賃のお支払い</dt>
                <dd class="formInput-inner" id="js-home_loan_flg">お支払いあり</dd>
            </dl>
            <dl class="formInput-box">
                <dt class="formInput-title">預貯金額</dt>
                <dd class="formInput-inner" id="js-deposit_amount"></dd>
            </dl>
        </div>
     </div>

     <div class="btn-area">
        <a href="/example/" class="btn btn-default">用例に戻る</a>
    </div>
</div>